### ISSUE TITLE
Keybinds not setting properly

### ISSUE THREAD

**Issue by benbrockn** [Prazon/SPBF-Issues#17]
## System Information
- CPU: Ryzen 2700
- GPU: GTX-1080
   - Driver/LLVM version: Nvidia 410.78
- OS:  Xubuntu 18.04.1 LTS 64-bit

## Symptoms 

When selecting different buttons as inputs, all 4 trigger/bumper buttons only use the shield.

**Comment by chui2ch** [comment]
This is also happening to me on Ubuntu 18.04.2 with a Xbox one S controller, Logitech F310, and DS4. Deleting the input.ini in Super Powered Battle Friends/SPBF/Saved/Config/LinuxNoEditor resets the controls back to default, and allows me to play.

**Comment by Prazon** [comment]
It's fixed in latest build however your broken inputs will carry over from last update, switching to Alternative or Default will reset them and fill them with proper inputs and allow you to put in your own. Saving them is still an issue as pressing Default or Alternative will replace them with the default inputs for those categories
